# PowerShell script to populate FTEQW_UWP.vcxproj with source files
# This script scans the engine directories and adds appropriate .c files to the project

Write-Host "FTEQW UWP Project File Populator" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan
Write-Host ""

$projectFile = "FTEQW_UWP.vcxproj"
$baseDir = ".."

# Files to exclude (platform-specific implementations)
$excludeFiles = @(
    "sys_win.c", "sys_linux.c", "sys_sdl.c", "sys_xdk.c", "sys_axfte.cpp", 
    "sys_droid.c", "sys_dos.c", "sys_morphos.c", "sys_plugfte.c",
    "in_win.c", "in_sdl.c", "in_linux.c",
    "cd_win.c", "cd_linux.c", "cd_sdl.c",
    "snd_win.c", "snd_linux.c", "snd_sdl.c", "snd_al.c", "snd_directx.c",
    "sv_sys_win.c", "sv_sys_unix.c",
    "net_ssl_winsspi.c", "net_ssl_gnutls.c", "net_ssl_openssl.c",
    "fs_win32.c", "fs_stdio.c",
    "sys_win_threads.c"
)

# Directories to scan
$sourceDirs = @(
    @{Path="client"; Include=@("*.c"); Priority=1},
    @{Path="common"; Include=@("*.c"); Priority=2},
    @{Path="d3d"; Include=@("d3d11*.c", "vid_d3d11.c"); Priority=3},
    @{Path="gl"; Include=@("*.c"); Priority=4},
    @{Path="http"; Include=@("*.c"); Priority=5},
    @{Path="qclib"; Include=@("*.c"); Priority=6},
    @{Path="server"; Include=@("*.c"); Priority=7}
)

Write-Host "Scanning directories for source files..." -ForegroundColor Yellow

$sourceFiles = @()

foreach ($dir in $sourceDirs) {
    $dirPath = Join-Path $baseDir $dir.Path
    
    if (Test-Path $dirPath) {
        Write-Host "  Scanning $($dir.Path)..." -ForegroundColor Gray
        
        foreach ($pattern in $dir.Include) {
            $files = Get-ChildItem -Path $dirPath -Filter $pattern -File | 
                Where-Object { $excludeFiles -notcontains $_.Name } |
                ForEach-Object {
                    $relativePath = "..\$($dir.Path)\$($_.Name)"
                    [PSCustomObject]@{
                        Path = $relativePath
                        Name = $_.Name
                        Priority = $dir.Priority
                    }
                }
            
            $sourceFiles += $files
        }
    } else {
        Write-Host "  Warning: Directory not found: $dirPath" -ForegroundColor Red
    }
}

# Sort by priority and name
$sourceFiles = $sourceFiles | Sort-Object Priority, Name

Write-Host ""
Write-Host "Found $($sourceFiles.Count) source files" -ForegroundColor Green
Write-Host ""

# Generate XML for ItemGroup
$xml = @"
  <ItemGroup>
    <!-- Auto-generated source file list -->
    <!-- Generated by populate_project.ps1 -->
    <ClCompile Include="..\client\sys_uwp.c">
      <ExcludedFromBuild Condition="'`$(Configuration)|`$(Platform)'=='Debug|ARM64'">false</ExcludedFromBuild>
      <ExcludedFromBuild Condition="'`$(Configuration)|`$(Platform)'=='Debug|x64'">false</ExcludedFromBuild>
      <ExcludedFromBuild Condition="'`$(Configuration)|`$(Platform)'=='Release|ARM64'">false</ExcludedFromBuild>
      <ExcludedFromBuild Condition="'`$(Configuration)|`$(Platform)'=='Release|x64'">false</ExcludedFromBuild>
    </ClCompile>
"@

foreach ($file in $sourceFiles) {
    $xml += "`n    <ClCompile Include=`"$($file.Path)`" />"
}

$xml += @"

  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" />
    <None Include="UWP_PORTING_GUIDE.md" />
    <None Include="IMPLEMENTATION_SUMMARY.md" />
    <None Include="BUILD_INSTRUCTIONS.md" />
    <None Include="Assets\README.md" />
  </ItemGroup>
"@

Write-Host "Generated ItemGroup XML:" -ForegroundColor Cyan
Write-Host $xml -ForegroundColor Gray
Write-Host ""

# Read current project file
if (Test-Path $projectFile) {
    $content = Get-Content $projectFile -Raw
    
    # Find and replace the ItemGroup section
    # Look for the section between <!-- Main platform file --> and <AppxManifest
    $pattern = '(?s)  <ItemGroup>.*?<!-- Main platform file -->.*?</ItemGroup>\s*<ItemGroup>.*?</ItemGroup>'
    
    if ($content -match $pattern) {
        $newContent = $content -replace $pattern, $xml
        
        # Backup original
        $backupFile = "$projectFile.backup"
        Copy-Item $projectFile $backupFile -Force
        Write-Host "Created backup: $backupFile" -ForegroundColor Yellow
        
        # Write new content
        Set-Content -Path $projectFile -Value $newContent -NoNewline
        Write-Host "Updated $projectFile successfully!" -ForegroundColor Green
        Write-Host ""
        Write-Host "Next steps:" -ForegroundColor Cyan
        Write-Host "1. Open FTEQW_UWP.sln in Visual Studio" -ForegroundColor White
        Write-Host "2. Select your platform (x64 or ARM64)" -ForegroundColor White
        Write-Host "3. Build the project (Ctrl+Shift+B)" -ForegroundColor White
    } else {
        Write-Host "Error: Could not find ItemGroup section to replace" -ForegroundColor Red
        Write-Host "You may need to manually add files via Visual Studio" -ForegroundColor Yellow
    }
} else {
    Write-Host "Error: Project file not found: $projectFile" -ForegroundColor Red
}

Write-Host ""
Write-Host "Done!" -ForegroundColor Green
