#!/bin/bash
# Bash script to populate FTEQW_UWP.vcxproj with source files
# This script scans the engine directories and adds appropriate .c files to the project

echo "FTEQW UWP Project File Populator"
echo "================================="
echo ""

PROJECT_FILE="FTEQW_UWP.vcxproj"
BASE_DIR=".."

# Files to exclude (platform-specific implementations)
EXCLUDE_FILES=(
    "sys_win.c" "sys_linux.c" "sys_sdl.c" "sys_xdk.c" "sys_axfte.cpp"
    "sys_droid.c" "sys_dos.c" "sys_morphos.c" "sys_plugfte.c"
    "in_win.c" "in_sdl.c" "in_linux.c"
    "cd_win.c" "cd_linux.c" "cd_sdl.c"
    "snd_win.c" "snd_linux.c" "snd_sdl.c" "snd_al.c" "snd_directx.c"
    "sv_sys_win.c" "sv_sys_unix.c"
    "net_ssl_winsspi.c" "net_ssl_gnutls.c" "net_ssl_openssl.c"
    "fs_win32.c" "fs_stdio.c"
    "sys_win_threads.c"
)

# Function to check if file should be excluded
should_exclude() {
    local file="$1"
    for exclude in "${EXCLUDE_FILES[@]}"; do
        if [ "$file" = "$exclude" ]; then
            return 0
        fi
    done
    return 1
}

echo "Scanning directories for source files..."

SOURCE_FILES=""

# Scan client directory
if [ -d "$BASE_DIR/client" ]; then
    echo "  Scanning client..."
    for file in "$BASE_DIR/client"/*.c; do
        filename=$(basename "$file")
        if ! should_exclude "$filename"; then
            SOURCE_FILES+="    <ClCompile Include=\"..\\client\\$filename\" />\n"
        fi
    done
fi

# Scan common directory
if [ -d "$BASE_DIR/common" ]; then
    echo "  Scanning common..."
    for file in "$BASE_DIR/common"/*.c; do
        filename=$(basename "$file")
        if ! should_exclude "$filename"; then
            SOURCE_FILES+="    <ClCompile Include=\"..\\common\\$filename\" />\n"
        fi
    done
fi

# Scan d3d directory (only D3D11 files)
if [ -d "$BASE_DIR/d3d" ]; then
    echo "  Scanning d3d..."
    for file in "$BASE_DIR/d3d"/d3d11*.c "$BASE_DIR/d3d"/vid_d3d11.c; do
        if [ -f "$file" ]; then
            filename=$(basename "$file")
            SOURCE_FILES+="    <ClCompile Include=\"..\\d3d\\$filename\" />\n"
        fi
    done
fi

# Scan gl directory
if [ -d "$BASE_DIR/gl" ]; then
    echo "  Scanning gl..."
    for file in "$BASE_DIR/gl"/*.c; do
        filename=$(basename "$file")
        SOURCE_FILES+="    <ClCompile Include=\"..\\gl\\$filename\" />\n"
    done
fi

# Scan http directory
if [ -d "$BASE_DIR/http" ]; then
    echo "  Scanning http..."
    for file in "$BASE_DIR/http"/*.c; do
        filename=$(basename "$file")
        SOURCE_FILES+="    <ClCompile Include=\"..\\http\\$filename\" />\n"
    done
fi

# Scan qclib directory
if [ -d "$BASE_DIR/qclib" ]; then
    echo "  Scanning qclib..."
    for file in "$BASE_DIR/qclib"/*.c; do
        filename=$(basename "$file")
        SOURCE_FILES+="    <ClCompile Include=\"..\\qclib\\$filename\" />\n"
    done
fi

# Scan server directory
if [ -d "$BASE_DIR/server" ]; then
    echo "  Scanning server..."
    for file in "$BASE_DIR/server"/*.c; do
        filename=$(basename "$file")
        if ! should_exclude "$filename"; then
            SOURCE_FILES+="    <ClCompile Include=\"..\\server\\$filename\" />\n"
        fi
    done
fi

echo ""
echo "Generating project file content..."

# Generate complete ItemGroup XML
XML_CONTENT="  <ItemGroup>
    <!-- Auto-generated source file list -->
    <!-- Generated by populate_project.sh -->
    <ClCompile Include=\"..\\client\\sys_uwp.c\" />
$SOURCE_FILES  </ItemGroup>
  <ItemGroup>
    <None Include=\"README.md\" />
    <None Include=\"UWP_PORTING_GUIDE.md\" />
    <None Include=\"IMPLEMENTATION_SUMMARY.md\" />
    <None Include=\"BUILD_INSTRUCTIONS.md\" />
    <None Include=\"Assets\\README.md\" />
  </ItemGroup>"

echo "Files scanned successfully!"
echo ""
echo "To update the project file:"
echo "1. Open $PROJECT_FILE in a text editor"
echo "2. Replace the ItemGroup section containing source files"
echo "3. With the content shown above"
echo ""
echo "Or manually add files via Visual Studio:"
echo "1. Open FTEQW_UWP.sln in Visual Studio"
echo "2. Right-click project -> Add -> Existing Item"
echo "3. Navigate to ../client, ../common, etc."
echo "4. Add .c files (excluding platform-specific ones)"
echo ""
echo "See BUILD_INSTRUCTIONS.md for detailed steps."
echo ""
echo "Done!"
